use_frameworks!

platform :ios, '8.0'

target 'PPBadgeView_Example' do
  pod 'PPBadgeView', :path => '../'

  target 'PPBadgeView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
